from typing import Optional, Protocol, Sequence, TypeVar, Union, runtime_checkable

from pydantic import BaseModel

from app.models.base_model import Base

ModelType = TypeVar("ModelType", bound=Union[Base, BaseModel], covariant=True)
CreateSchemaType = TypeVar("CreateSchemaType", bound=BaseModel, contravariant=True)
UpdateSchemaType = TypeVar("UpdateSchemaType", bound=BaseModel, contravariant=True)


@runtime_checkable
class AbstractRepository(Protocol[ModelType, CreateSchemaType, UpdateSchemaType]):
    async def create(self, data: CreateSchemaType, *args, **kwargs) -> ModelType: ...
    async def find_one(self, *args, **kwargs) -> Optional[ModelType]: ...
    async def find_all(self, *args, **kwargs) -> Sequence[ModelType]: ...
    async def update(self, data: UpdateSchemaType, *args, **kwargs) -> ModelType: ...
    async def delete(self, *args, **kwargs) -> None: ...
    async def exists(self, *args, **kwargs) -> bool: ...
